# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gazette}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Pollard"]
  s.date = %q{2010-12-03}
  s.description = %q{Simple Ruby wrapper gem to interact with the Instapaper API.  Supports authenticate and add API methods, as well as https, jsonp and all other features of the API.}
  s.email = %q{jeff.pollard@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "gazette.gemspec",
     "lib/gazette.rb",
     "lib/gazette/api.rb",
     "lib/gazette/client.rb",
     "lib/gazette/response.rb",
     "lib/gazette/response/error.rb",
     "lib/gazette/response/success.rb",
     "spec/client/add_spec.rb",
     "spec/client/authenticate_spec.rb",
     "spec/client/client_spec.rb",
     "spec/response/error_spec.rb",
     "spec/response/success_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "todo.txt"
  ]
  s.homepage = %q{http://github.com/Fluxx/gazette}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby library to interact with the Instapaper API.}
  s.test_files = [
    "spec/client/add_spec.rb",
     "spec/client/authenticate_spec.rb",
     "spec/client/client_spec.rb",
     "spec/response/error_spec.rb",
     "spec/response/success_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

